export let arrayOfCountries = [
    {
      id: 1,
      name: "United States",
      population: 331002651,
      cities: ["New York", "Los Angeles", "Chicago"],
    },
    {
      id: 2,
      name: "China",
      population: 1444216107,
      cities: ["Beijing", "Shanghai", "Guangzhou"],
    },
    {
      id: 3,
      name: "India",
      population: 1380004385,
      cities: ["Mumbai", "Delhi", "Bangalore"],
    },
    {
      id: 4,
      name: "Brazil",
      population: 212559417,
      cities: ["Sao Paulo", "Rio de Janeiro", "Brasilia"],
    },
    {
      id: 5,
      name: "United Kingdom",
      population: 67886011,
      cities: ["London", "Manchester", "Birmingham"],
    },
    {
      id: 6,
      name: "Canada",
      population: 37742154,
      cities: ["Toronto", "Vancouver", "Montreal"],
    },
    {
      id: 7,
      name: "Australia",
      population: 25499884,
      cities: ["Sydney", "Melbourne", "Brisbane"],
    },
    {
      id: 8,
      name: "Japan",
      population: 126476461,
      cities: ["Tokyo", "Osaka", "Kyoto"],
    },
    {
      id: 9,
      name: "Germany",
      population: 83783942,
      cities: ["Berlin", "Munich", "Hamburg"],
    },
    {
      id: 10,
      name: "South Africa",
      population: 59308690,
      cities: ["Johannesburg", "Cape Town", "Pretoria"],
    },
    {
      id: 11,
      name: "France",
      population: 65273511,
      cities: ["Paris", "Marseille", "Lyon"],
    },
    {
      id: 12,
      name: "Mexico",
      population: 128932753,
      cities: ["Mexico City", "Guadalajara", "Monterrey"],
    },
    {
      id: 13,
      name: "Spain",
      population: 46754778,
      cities: ["Madrid", "Barcelona", "Valencia"],
    },
    {
      id: 14,
      name: "Russia",
      population: 145912025,
      cities: ["Moscow", "Saint Petersburg", "Novosibirsk"],
    },
    {
      id: 15,
      name: "Nigeria",
      population: 206139587,
      cities: ["Lagos", "Kano", "Ibadan"],
    },
    {
      id: 16,
      name: "Italy",
      population: 60461826,
      cities: ["Rome", "Milan", "Naples"],
    },
    {
      id: 17,
      name: "Argentina",
      population: 45195777,
      cities: ["Buenos Aires", "Cordoba", "Rosario"],
    },
    {
      id: 18,
      name: "Egypt",
      population: 102334404,
      cities: ["Cairo", "Alexandria", "Giza"],
    },
    {
      id: 19,
      name: "Saudi Arabia",
      population: 34813871,
      cities: ["Riyadh", "Jeddah", "Mecca"],
    },
    {
      id: 20,
      name: "Thailand",
      population: 69799978,
      cities: ["Bangkok", "Chiang Mai", "Phuket"],
    },
    {
      id: 21,
      name: "Indonesia",
      population: 273523615,
      cities: ["Jakarta", "Surabaya", "Bandung"],
    },
    {
      id: 22,
      name: "Turkey",
      population: 84339067,
      cities: ["Istanbul", "Ankara", "Izmir"],
    },
    {
      id: 23,
      name: "South Korea",
      population: 51269185,
      cities: ["Seoul", "Busan", "Incheon"],
    },
    {
      id: 24,
      name: "Czech Republic",
      population: 10708981,
      cities: ["Prague", "Brno", "Ostrava"],
    },
    {
      id: 25,
      name: "Greece",
      population: 10423054,
      cities: ["Athens", "Thessaloniki", "Patras"],
    },
    {
      id: 26,
      name: "Canada",
      population: 37742154,
      cities: ["Toronto", "Vancouver", "Montreal"],
    },
    {
      id: 27,
      name: "New Zealand",
      population: 4822233,
      cities: ["Auckland", "Wellington", "Christchurch"],
    },
    {
      id: 28,
      name: "Peru",
      population: 32971854,
      cities: ["Lima", "Arequipa", "Trujillo"],
    },
    {
      id: 29,
      name: "Kenya",
      population: 53771296,
      cities: ["Nairobi", "Mombasa", "Kisumu"],
    },
    {
      id: 30,
      name: "Sweden",
      population: 10099265,
      cities: ["Stockholm", "Gothenburg", "Malmö"],
    },
    {
      id: 31,
      name: "Ireland",
      population: 4937786,
      cities: ["Dublin", "Cork", "Galway"],
    },
    {
      id: 32,
      name: "Netherlands",
      population: 17134872,
      cities: ["Amsterdam", "Rotterdam", "The Hague"],
    },
    {
      id: 33,
      name: "Belgium",
      population: 11589623,
      cities: ["Brussels", "Antwerp", "Ghent"],
    },
    {
      id: 34,
      name: "Poland",
      population: 37846611,
      cities: ["Warsaw", "Krakow", "Wroclaw"],
    },
    {
      id: 35,
      name: "Switzerland",
      population: 8654622,
      cities: ["Zurich", "Geneva", "Bern"],
    },
    {
      id: 36,
      name: "Austria",
      population: 9006398,
      cities: ["Vienna", "Graz", "Linz"],
    },
    {
      id: 37,
      name: "Portugal",
      population: 10196709,
      cities: ["Lisbon", "Porto", "Vila Nova de Gaia"],
    },
    {
        id: 70,
        name: "Tajikistan",
        population: 9537640,
        cities: ["Dushanbe", "Khujand", "Qurghonteppa"],
    },
    {
        id: 39,
        name: "Denmark",
        population: 5792202,
        cities: ["Copenhagen", "Aarhus", "Odense"],
      },
      {
        id: 40,
        name: "Norway",
        population: 5421241,
        cities: ["Oslo", "Bergen", "Trondheim"],
      },
      {
        id: 41,
        name: "Finland",
        population: 5540720,
        cities: ["Helsinki", "Tampere", "Turku"],
      },
      {
        id: 42,
        name: "Singapore",
        population: 5850342,
        cities: ["Singapore City"],
      },
      {
        id: 43,
        name: "Malaysia",
        population: 32365999,
        cities: ["Kuala Lumpur", "George Town", "Ipoh"],
      },
      {
        id: 44,
        name: "Vietnam",
        population: 97338579,
        cities: ["Ho Chi Minh City", "Hanoi", "Da Nang"],
      },
      {
        id: 45,
        name: "South Africa",
        population: 59308690,
        cities: ["Johannesburg", "Cape Town", "Pretoria"],
      },
      {
        id: 46,
        name: "Morocco",
        population: 36910560,
        cities: ["Casablanca", "Rabat", "Fes"],
      },
      {
        id: 47,
        name: "Chile",
        population: 19116201,
        cities: ["Santiago", "Valparaíso", "Concepción"],
      },
      {
        id: 48,
        name: "Colombia",
        population: 50882891,
        cities: ["Bogotá", "Medellín", "Cali"],
      },
      {
        id: 49,
        name: "Venezuela",
        population: 28435940,
        cities: ["Caracas", "Maracaibo", "Valencia"],
      },
      {
        id: 50,
        name: "Ukraine",
        population: 44385155,
        cities: ["Kyiv", "Kharkiv", "Odesa"],
      },
      {
        id: 51,
        name: "Romania",
        population: 19237691,
        cities: ["Bucharest", "Cluj-Napoca", "Timișoara"],
      },
      {
        id: 52,
        name: "Ghana",
        population: 31072940,
        cities: ["Accra", "Kumasi", "Tamale"],
      },
      {
        id: 53,
        name: "Ethiopia",
        population: 114963588,
        cities: ["Addis Ababa", "Dire Dawa", "Mek'ele"],
      },
      {
        id: 54,
        name: "Kenya",
        population: 53771296,
        cities: ["Nairobi", "Mombasa", "Kisumu"],
      },
      {
        id: 55,
        name: "New Zealand",
        population: 4822233,
        cities: ["Auckland", "Wellington", "Christchurch"],
      },
      {
        id: 56,
        name: "Philippines",
        population: 113253240,
        cities: ["Manila", "Cebu City", "Davao City"],
      },
      {
        id: 57,
        name: "Maldives",
        population: 521000,
        cities: ["Male"],
      },
      {
        id: 58,
        name: "Austria",
        population: 9006398,
        cities: ["Vienna", "Graz", "Linz"],
      },
      {
        id: 59,
        name: "Croatia",
        population: 4105267,
        cities: ["Zagreb", "Split", "Rijeka"],
      },
      {
        id: 60,
        name: "Cuba",
        population: 11326616,
        cities: ["Havana", "Santiago de Cuba", "Camagüey"],
      },
      {
        id: 61,
        name: "Dominican Republic",
        population: 10847910,
        cities: ["Santo Domingo", "Santiago", "La Romana"],
      },
      {
        id: 62,
        name: "Ecuador",
        population: 17643054,
        cities: ["Quito", "Guayaquil", "Cuenca"],
      },
      {
        id: 63,
        name: "Iceland",
        population: 356991,
        cities: ["Reykjavik", "Kopavogur", "Hafnarfjordur"],
      },
      {
        id: 64,
        name: "Jamaica",
        population: 2961161,
        cities: ["Kingston", "Spanish Town", "Montego Bay"],
      },
      {
        id: 65,
        name: "Kuwait",
        population: 4270571,
        cities: ["Kuwait City", "Hawalli", "Salmiya"],
      },
      {
        id: 66,
        name: "Lebanon",
        population: 6825442,
        cities: ["Beirut", "Tripoli", "Sidon"],
      },
      {
        id: 67,
        name: "Luxembourg",
        population: 625978,
        cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"],
      },
      {
        id: 68,
        name: "Nepal",
        population: 29136808,
        cities: ["Kathmandu", "Pokhara", "Patan"],
      },
      {
        id: 69,
        name: "Oman",
        population: 5106626,
        cities: ["Muscat", "Seeb", "Salalah"],
       },
       {
        id: 70,
        name: "Panama",
        population: 4314767,
        cities: ["Panama City", "San Miguelito", "Tocumen"],
       },
       {
        id: 71,
        name: "Qatar",
        population: 2881053,
        cities: ["Doha", "Al Rayyan", "Umm Salal Muhammad"],
        },
        {
        id: 72,
        name: "Rwanda",
        population: 12952218,
        cities: ["Kigali", "Butare", "Gitarama"],
        },     
        {
        id: 73,
        name: "Sri Lanka",
        population: 21413250,
        cities: ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa"],
        },  
        {
        id: 74,
        name: "Tanzania",
        population: 59734218,
        cities: ["Dodoma", "Dar es Salaam", "Mwanza"],
        },   
        {
        id: 75,
        name: "Uganda",
        population: 45741007,
        cities: ["Kampala", "Gulu", "Lira"],
        },
        {
        id: 76,
        name: "Zimbabwe",
        population: 14862924,
        cities: ["Harare", "Bulawayo", "Chitungwiza"],
        },
        {
        id: 77,
        name: "Algeria",
        population: 43851044,
        cities: ["Algiers", "Oran", "Constantine"],
         },
        {
        id: 79,
        name: "Tunisia",
        population: 11818619,
        cities: ["Tunis", "Sfax", "Sousse"],
        },
        {
        id: 80,
        name: "Libya",
        population: 6871292,
        cities: ["Tripoli", "Benghazi", "Misrata"],
        },
        {
        id: 81,
        name: "Greece",
        population: 10423054,
        cities: ["Athens", "Thessaloniki", "Patras"],
        },
        {
        id: 82,
        name: "Israel",
        population: 8655535,
        cities: ["Jerusalem", "Tel Aviv", "Haifa"],
        },
        {
        id: 83,
        name: "Palestine",
        population: 5101414,
        cities: ["Gaza City", "Ramallah", "Hebron"],
        },
        {
        id: 84,
        name: "Jordan",
        population: 10203134,
        cities: ["Amman", "Zarqa", "Irbid"],
        },
        {
        id: 85,
        name: "Bahrain",
        population: 1701583,
        cities: ["Manama", "Riffa", "Muharraq"],
        },
        {
        id: 86,
        name: "United Arab Emirates",
        population: 9890402,
        cities: ["Dubai", "Abu Dhabi", "Sharjah"],
        },
        {
        id: 87,
        name: "Kazakhstan",
        population: 187,
        cities:[]
        },
        {
            id: 88,
            name: "Equatorial Guinea",
            population: 1402985,
            cities: ["Malabo", "Bata", "Ebebiyin"],
          },
          {
            id: 89,
            name: "Sao Tome and Principe",
            population: 219159,
            cities: ["Sao Tome"],
          },
          {
            id: 90,
            name: "Western Sahara",
            population: 597339,
            cities: ["Laayoune"],
          },
          {
            id: 91,
            name: "Mauritius",
            population: 1271768,
            cities: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix"],
          },
          {
            id: 92,
            name: "Seychelles",
            population: 98347,
            cities: ["Victoria", "Anse Boileau", "Beau Vallon"],
          },
          {
            id: 93,
            name: "Comoros",
            population: 869601,
            cities: ["Moroni", "Mutsamudu", "Fomboni"],
          }
    ];
    
    